feat(update dockerfile): update dockerfile

diff --git a/_appconfig/Dockerfile b/_appconfig/Dockerfile
--- a/_appconfig/Dockerfile
+++ b/_appconfig/Dockerfile
@@ -1,13 +1,55 @@
 FROM registry.qunhequnhe.com/infra/base-builder-v16:latest as builder
-RUN mkdir /approot
-COPY . /approot
-RUN cd /approot && \
-yarn 
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-FROM registry.qunhequnhe.com/infra/node16:latest
-RUN mkdir /approot
-WORKDIR /approot
-COPY --from=builder /approot /approot
-RUN ls /approot
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-CMD scfConfig=${SCFCONFIG} stage=${STAGE} domain=${DOMAIN} region=${REGION} functions=${SELECTFUNCS} yarn start
+
+# Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN yarn build
+
+# If using npm comment out above and use below instead
+# RUN npm run build
+
+# Production image, copy all the files and run next
+FROM  registry.qunhequnhe.com/infra/base-builder-v16:latest AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 8000
+
+ENV PORT 8000
+
+CMD ["node", "server.js"]
